
/* File generated by gen_cfile.py. Should not be modified. */

#ifndef MASTER_H
#define MASTER_H

#include "data.h"

/* Prototypes of function provided by object dictionnary */
UNS32 Master_valueRangeTest (UNS8 typeValue, void * value);
const indextable * Master_scanIndexOD (CO_Data *d, UNS16 wIndex, UNS32 * errorCode);

/* Master node data struct */
extern CO_Data Master_Data;
extern UNS16 controlWord_6040[2];		/* Mapped at index 0x2000, subindex 0x01 - 0x02 */
extern INTEGER8 modeOfOperation_6060[2];		/* Mapped at index 0x2001, subindex 0x01 - 0x02 */
extern INTEGER32 targetPosition_607A[2];		/* Mapped at index 0x2002, subindex 0x01 - 0x02 */
extern UNS32 profileVelocity_6081[2];		/* Mapped at index 0x2003, subindex 0x01 - 0x02 */
extern UNS16 statusWord_6041[2];		/* Mapped at index 0x2004, subindex 0x01 - 0x02 */
extern INTEGER32 positionActualValue_6063[2];		/* Mapped at index 0x2005, subindex 0x01 - 0x02 */
extern INTEGER32 velocityActualValue_606C[2];		/* Mapped at index 0x2006, subindex 0x01 - 0x02 */
extern INTEGER32 targetVelocity_60FF[2];		/* Mapped at index 0x2007, subindex 0x01 - 0x02 */
extern UNS32 profileAcceleration_6083[2];		/* Mapped at index 0x2008, subindex 0x01 - 0x02 */
extern UNS32 profileDeceleration_6084[2];		/* Mapped at index 0x2009, subindex 0x01 - 0x02 */
extern UNS16 errorWord1[2];		/* Mapped at index 0x200A, subindex 0x01 - 0x02 */
extern UNS16 readControlWord[2];		/* Mapped at index 0x200B, subindex 0x01 - 0x02 */
extern INTEGER8 readOperateMode[2];		/* Mapped at index 0x200C, subindex 0x01 - 0x02 */
extern UNS16 errorWord2[2];		/* Mapped at index 0x200D, subindex 0x01 - 0x02 */
extern UNS16 Sensor_Din[2];		/* Mapped at index 0x200E, subindex 0x01 - 0x02 */

#endif // MASTER_H
